### PR TITLE
u765: handle multiple copies of "weak" sectors

### PR DESCRIPTION
**Pull request by gyurco**
Tested with Operation Wolf and Afterburner.

### CODE REVIEW

**Comment by sorgelig** [comment]
By the way, it would be good to add Drive B support in u765.
It can be made easier way. Just add a signal to u765 which will allow to react u765 when matched disk is selected.
Every drive can include its own copy of u765 just like i did in wd1793 (but not used in spectrum).
You don't need to adapt the Amstrad code for second drive support - i will do this. I just need updated u765.

**Comment by gyurco** [comment]
Ok, I'll try, actually 2 bits can be added, since the upd765 can handle 4 drives. However not sure if AMSDOS supports 4. I guess there won't be MiST support, at least not for 2 read-write images.

One of the problems I see that the usually the command's second byte which chooses the disk drive, so the first byte will change from the idle state to a command state, then according to the second byte sent to the data port, the appropriate upd765 instance will either continue or return to the idle state.
Also there's a problem with the main status register, which is common for all drives. Another thing is that duplicate the u765 will surely cause timing problems :) (maybe not at 64 MHz).

**Comment by sorgelig** [comment]
Hold on. I will modify u765 by myself. I just recalled MiST doesn't support mounting of more than 1 image. On;y MiSTer supports multiple image mounting. So, i will do modification by myself first. Actually, i've done it already. Need some testing. You will correct if you will need to.

**Comment by gyurco** [comment]
Yepp, that would be a feature which I cannot test :(
I'm curious how can you solve with 2 instances, but it wouldn't be so hard to duplicate some structures inside the FDC to support 2 drivers, and index them with the ds0 bit (usually bit0 of the second command byte). Fortunately the only command which can run parallel is the seek (and recalibrate), every other command must be finished before issued to another drive.

**Comment by gyurco** [comment]
Btw what signals MiSTer sends for the second image?

**Comment by sorgelig** [comment]
Duplicating structures inside the u765 is more correct way, but not so easy. Especially for me who doesn't understand every bit of this module :) So, i can do light modifications inside and just duplicate the whole u765. Only main status register will be OR'ed between instances.
But once i finish it, you can rewrite it for internal multidrive support :)

**Comment by gyurco** [comment]
Well, I tried to write clean code, but I was just partially successful, I guess :)
Another strange thing: did you notice anything which prevents ROM writes? Seems you can write into ROM areas.

**Comment by sorgelig** [comment]
Amstrad_MMU module has protection against ROM writes. It should write to RAM mapped to the same area instead.

**Comment by gyurco** [comment]
I think "OR"-ing the main status register would not really work, e.g. bit 7 is the "ready for next byte" bit, it'll be always 1, if the currently idleing controllers are setting to 1 this bit. (ANDing this bit maybe works). Then there is the transfer direction bit, idleing controllers waits a byte from the CPU (0), probably this bit must be ORed. And I see other problems which I cannot even describe :)

**Comment by sorgelig** [comment]
I have special handling for bit 7 :)

**Comment by sorgelig** [comment]
I've spent several hours to find why Quartus crashes.. And it turned out because of the same signal name inside the always clause and outside(global)! It doesn't tell about error(although it's not a error actually) - it simply crashes. Good behavior!

**Comment by gyurco** [comment]
Strange error, mine crashes when it tries to use openssl installed on the system :)
So will 2 upd765 work? I would see the code :)

Meanwhile I finished the Multiface 2 code, and it worked well! Until I update the core, and got the CPC664 :) It works only on the 6128.
If I put only one MF2 ROM at the end of the file, the new SDRAM module will handle only on boot_bank=0 (or 1), which is the machine type, but not both? Then should I put the ROM twice to the end of amstrad.rom, or is it another method?

**Comment by sorgelig** [comment]
It depends on how you handle it. Currently only standard parts are handled. You may include MF2 ROM twice. It will be more flexible as later it will be possible to have different ROMs for different models. I didn't release CPC664 support yet, so ROMs can be re-arranged: 4 ROMs for 6128 and then another 4 ROMs for 664

**Comment by gyurco** [comment]
I like this rearrangement, I'll do it then.

**Comment by sorgelig** [comment]
I've updated MiSTer version with all recent changes.
MiSTer got 2 new features not implemented in MiST:
- Drive B support.
- Expansion ROM loading.

**Comment by gyurco** [comment]
I see, ugly but efficient :)
Now I know what signals MiSTer uses for the dual-drive setup, I can make the change to the upd765 to handle two drives internally. However don't expect a fast conversion, probably need some weeks to do it.

**Comment by sorgelig** [comment]
For expansion ROM loading there were actually only 2 options. I could define the header in ROM of 1 byte with page, but this would be not convenient for most users as not many people are familiar with hex editors. So, i've choose dummy but user friendly method :)

**Comment by gyurco** [comment]
Yepp, as I see it's the same as in the original core. I'm wondering if an .ff extension will overwrite the Multiface ROM or not (or mapping the FF rom will make the MF2 ROM visible in the upper area?). Maybe I've choosen its address wrongly?

**Comment by sorgelig** [comment]
.eFF will overwrite the ROM in FF page. The same as eZZ, e00, e07 will overwrite system ROMs as well. I let it intentionally, so user can enable other configs temporary without modifying the system ROM file.

**Comment by sorgelig** [comment]
.eZ0 with CPC464 OS+BASIC will enable CPC464 mode without making a separate option in OSD.

**Comment by gyurco** [comment]
I understand, but if FF will load to '1ff, then MF2 ROM is in danger. Or just misunderstood something?

**Comment by sorgelig** [comment]
If you would like to load eFF ROM, then why not? Simply don't load eFF if you don't need. It's impossible to replace the ROM without explicitly select it in OSD. So, i don't see any danger here.

**Comment by gyurco** [comment]
But won't you overwrite the Multiface ROM then?  Maybe it would be good to choose a new place for the MF2 ROM. It is also not meant to be paged in to the upper ROM area.

**Comment by sorgelig** [comment]
Yes, of course. Same as OS/BASIC/DOS ROMs :)

**Comment by sorgelig** [comment]
Someone may want to try other MF2 ROM version for example.

**Comment by gyurco** [comment]
Well, the original machine cannot map the MF2 ROM like any other extension ROMs :) Seems its just the side-effect of my wrongly chosen address.

**Comment by sorgelig** [comment]
Here is the demo seems having problem with disk access:
https://www.pouet.net/prod.php?which=75725
It works till Freddy Kruger picture then load quickly something from disk and hangs. I've tried with AMSDOS and PARADOS - result is the same. And probably demo doesn't use DOS ROM to access the disk.
The same demo with 2 disks works. Overall demo has glitches here and there but mostly works.
2 disk version is here: https://cpcrulez.fr/demostestDO_phx-condense.htm

**Comment by gyurco** [comment]
That's sure it doesn't use the DOS, since it cannot handle double sided disks (Speccy +3 can!). I put this on my TODO-list (after 2 FDDs and make original Operation Thunderbolt run).

**Comment by sorgelig** [comment]
2 FDD can wait as it works in its current form.

**Comment by gyurco** [comment]
I've already started the work on it, the only tricky part is to serialize the image loading (when inserting for the two drives concurrently), otherwise just some dull register duplication.

**Pull request merged**
