### PR TITLE
Timing tweaks

### PR DESCRIPTION
**Pull request by gyurco**
- 64MHz system clock, 128MHz SDRAM
- 8mA outputs to SDRAM, this means less delay
- timing constraints (even for the VGA pins)

(And changed the 2.5V output levels to 3.3V)

Don't know if you'll like it or not, but 64MHz system clock is nicer, I think (and it's synchronous to the 128MHz video clock).

### CODE REVIEW

**Comment by sorgelig** [comment]
Actually, letting SDRAM run on 128MHz is not a good idea. Although SDRAM chip is 133MHz, timings become very strict on these frequencies. Some boards may not work due to timing fluctuations from board to board. I remember some cores had problems due to this. 
That's why i've decided to use original 112MHz. 
I would rather see how zsdram module can be improved to reduce SDRAM clock to 64MHz. With system clock 4MHz, 64MHz should be enough to service the RAM. Even with 2 data channels.

**Comment by gyurco** [comment]
The AtariST core also uses the SDRAM on 128MHz, and no reports of being unstable (which is a miracle, because of the plethoria of async clocks in that core - there's about 40, and the Cyclone III has 20 global clock networks). It even doesn't use the dedicated clock path from the PLL to the SDCLK.

(Copy protection update: some which now loads in the core doesn't even load in an emulator on PC).

**Comment by sorgelig** [comment]
I've replaced CPU with my precise wrapper. Together with new WAIT_n states i get perfect dynamic color effects in Equinox demo. Probably timings are still need tweaks for other demos, but now it's much better than originally was.

Amstrad core got some metastability issue. Sometimes compilation produce the bitstream where WAIT_n states aren't working (Equinox demo is good quick test). Or sometimes you simply get black screen at start :)

**Comment by gyurco** [comment]
Oh, fantastic!
I will look at the timings, maybe adding |T80:u0 to the T80 constraints can help, since the top-level is not really for skipping clock cycles.
I also have a patch for zsdram which allows to use Fast IO Registers of the FPGA (not a big deal, just use input/output regs, not wires).
Meanwhile I'm working on a Multiface 2 implementation, I'm not as quick as you, but I hope I can send a pull request with a working Multiface this summer :)

**Pull request merged**
